# Generated by Django 4.1.7 on 2023-04-23 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_balance_amount_alter_balancetransfer_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancetransfer',
            options={'verbose_name': 'Transfer', 'verbose_name_plural': 'Transfers'},
        ),
        migrations.AddField(
            model_name='balancetransfer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
