# Generated by Django 4.1.7 on 2023-04-23 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_balancetransfer_options_balancetransfer_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='sender email')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='recipient email')),
                ('currency', models.CharField(choices=[('GBP', 'GBP (British Pound Sterling)'), ('USD', 'USD (United States Dollar)'), ('EUR', 'EUR (Euro)')], default='GBP', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('ACC', 'Accepted'), ('DEC', 'Declined')], default='PND', max_length=3)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
