# Generated by Django 4.1.7 on 2023-04-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_date_balancetransfer_created_at_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetransfer',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
