# Generated by Django 4.1.7 on 2023-04-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='change_password',
            field=models.BooleanField(default=False),
        ),
    ]

