# Generated by Django 4.1.7 on 2023-04-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_delete_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
